project 'ConnectMobileUser.xcodeproj'
platform :ios, '14.0'

target 'ConnectMobileUser' do
  pod 'AWSCore'
  pod 'AWSConnect'
  pod 'AWSConnectParticipant'
  pod 'AWSCognitoIdentityProvider'
  pod 'Alamofire', '~> 5.7'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'KeychainSwift', '~> 20.0'
  pod 'CocoaLumberjack/Swift', '~> 3.7'
end
